// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0wvNosir9Byu0pIz5aq1XeOLG9q8ovEI',
    appId: '1:478127570821:web:d0a9277dde114b8ab84eec',
    messagingSenderId: '478127570821',
    projectId: 'my-ship-3939d',
    authDomain: 'my-ship-3939d.firebaseapp.com',
    storageBucket: 'my-ship-3939d.appspot.com',
    measurementId: 'G-69H291KHBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5C0cj6gnLNIFgxcbjp7ZiwdDhuF8b-U',
    appId: '1:478127570821:android:ce62cd701bef4349b84eec',
    messagingSenderId: '478127570821',
    projectId: 'my-ship-3939d',
    storageBucket: 'my-ship-3939d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs_nhGNw9j63ossMyp0aFNRBw9fH_KvlY',
    appId: '1:478127570821:ios:cae48d61ce3bec54b84eec',
    messagingSenderId: '478127570821',
    projectId: 'my-ship-3939d',
    storageBucket: 'my-ship-3939d.appspot.com',
    iosClientId: '478127570821-sme5sr455lsaeljfu0j8tn5asnqrhgtb.apps.googleusercontent.com',
    iosBundleId: 'com.lmoc.dev.ship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs_nhGNw9j63ossMyp0aFNRBw9fH_KvlY',
    appId: '1:478127570821:ios:b2ff8354a2901368b84eec',
    messagingSenderId: '478127570821',
    projectId: 'my-ship-3939d',
    storageBucket: 'my-ship-3939d.appspot.com',
    iosClientId: '478127570821-2j6qt3tp4svc6rrl0ghtq55o2t6f5tok.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterShip',
  );
}
